# Generated by Django 3.1.6 on 2021-03-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Carousel Image', max_length=100)),
                ('image', models.ImageField(upload_to='CarouselImages/')),
            ],
        ),
    ]
