# Generated by Django 3.1.7 on 2021-03-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCard',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherImage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='TeacherImages/')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ashaAPI.teachercard')),
            ],
        ),
    ]
