# Generated by Django 3.1.7 on 2021-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0002_teachercard_teacherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercard',
            name='facultySubject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teachercard',
            name='isInManagements',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
