# Generated by Django 3.1.7 on 2021-03-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0004_auto_20210306_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField()),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
