# Generated by Django 3.1.7 on 2021-03-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0005_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField()),
                ('fileSubmission', models.FileField(upload_to='CVSubmissions/')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherimage',
            name='teacher',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachercard',
            name='teacherImage',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ashaAPI.teacherimage'),
        ),
    ]
