# Generated by Django 3.1.7 on 2021-03-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0007_auto_20210318_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherImage',
        ),
    ]
