# Generated by Django 3.1.7 on 2021-03-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0009_cvsubmission_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='subjectApplyingFor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ashaAPI.subject'),
        ),
    ]
