# Generated by Django 3.1.7 on 2021-03-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0011_auto_20210324_0540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherCard',
        ),
    ]
