# Generated by Django 3.1.7 on 2021-04-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0012_delete_teachercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsubmission',
            name='subjectApplyingFor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaAPI.subject'),
        ),
    ]
