# Generated by Django 3.1.7 on 2021-04-04 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaAPI', '0013_auto_20210402_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('description', models.TextField(default=True, null=True)),
            ],
        ),
    ]
