# Generated by Django 3.1.7 on 2021-03-26 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashaAPI', '0012_delete_teachercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('isInManagement', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('teacherImage', models.ImageField(upload_to='TeacherImages/')),
                ('facultySubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ashaAPI.subject')),
                ('teacherUserModel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
