# Generated by Django 3.1.7 on 2021-03-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='teacherID',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
