# Generated by Django 3.1.7 on 2021-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0002_teacherdata_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='isStudent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='isTeacher',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
