# Generated by Django 3.1.7 on 2021-03-26 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('classStudyingIn', models.IntegerField(default=8)),
                ('studentID', models.CharField(default='', max_length=100, unique=True)),
                ('parentName', models.CharField(default='', max_length=100)),
                ('studentImage', models.ImageField(blank=True, null=True, upload_to='StudentImages/')),
                ('parentPhoneNumber', models.IntegerField(max_length=10)),
                ('studentMainData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
