# Generated by Django 3.1.7 on 2021-03-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='parentPhoneNumber',
            field=models.IntegerField(),
        ),
    ]
