# Generated by Django 3.1.7 on 2021-03-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_auto_20210326_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='studentMainData',
            new_name='studentUserModel',
        ),
    ]
