# Generated by Django 3.1.7 on 2021-03-29 10:55

from django.db import migrations, models
import django.db.models.deletion
import student_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0003_auto_20210329_0717'),
        ('ashaAPI', '0012_delete_teachercard'),
        ('student_portal', '0004_auto_20210329_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('totalMarks', models.IntegerField()),
                ('obtainedMarks', models.IntegerField()),
                ('marksheetPDF', models.FileField(upload_to=student_portal.models.uploadToCallback)),
                ('checkedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_portal.teacherdata')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaAPI.subject')),
                ('writtenBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.studentdata')),
            ],
        ),
    ]
