# Generated by Django 3.1.7 on 2021-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_auto_20210330_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='attendancePercentage',
            field=models.IntegerField(default=100),
        ),
    ]
