# Generated by Django 3.1.7 on 2021-04-20 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import student_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0007_studentdata_attendancepercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='hasPayedFees',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentPaymentDetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('dateAndTimePaid', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('receipt', models.FileField(upload_to=student_portal.models.uploadToCallBackReceipt)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.studentdata')),
            ],
        ),
    ]
